services:
  db:
    container_name: todo-app-db
    image: postgres:16
    environment:
      POSTGRES_DB: todos_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - db_data:/var/lib/postgresql/data # Volume for persistent data
      - ./db/initdb/init.sql:/docker-entrypoint-initdb.d/init.sql # Mount the init script
    ports:
      - "5432:5432"

  backend:
    container_name: todo-app-backend
    build:
      context: ./backend/
      dockerfile: Dockerfile
    ports:
      - "7778:7778"
    environment:
      - DB_USER=user
      - DB_HOST=db
      - DB_NAME=todos_db
      - DB_PASSWORD=password
      - DB_PORT=5432
      - PORT=7778
      - DATABASE_URL=postgres://user:password@db:5432/todos_db
    depends_on:
      - db

  frontend-react-vite:
    container_name: todo-app-frontend-react-vite
    build:
      context: ./frontend/react-vite
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    depends_on:
      - backend
    volumes:
      - ./frontend/nginx/nginx.conf:/etc/nginx/conf.d/default.conf

volumes:
  db_data: {}