apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-app-backend-express
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo-app
      tier: backend
  template:
    metadata:
      labels:
        app: todo-app
        tier: backend
    spec:
      containers:
        - name: backend
          image: mtanfield/to-do-app-backend-express:latest
          ports:
            - containerPort: 7778
          env:
            - name: DB_USER
              value: "user"
            - name: DB_HOST
              value: "db-postgres"
            - name: DB_NAME
              value: "todos_db"
            - name: DB_PASSWORD
              value: "password"
            - name: DB_PORT
              value: "5432"
            - name: PORT
              value: "7778"
            - name: DATABASE_URL
              value: "postgres://user:password@db-postgres:5432/todos_db"
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "250m"
---
apiVersion: v1
kind: Service
metadata:
  name: backend-express
spec:
  selector:
    app: todo-app
    tier: backend
  ports:
    - protocol: TCP
      port: 7778
      targetPort: 7778
  type: ClusterIP